name: "SPFx CICD"
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  CI-SPFx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js runtime 
      - name: Node.js install
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Install npm
      - name: Run npm ci
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      # Bundle and Package
      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

    # Login M365 CLI
      - name: Login to M365 CLI
        shell: bash
        run:  m365 login --authType browser

      # Upload SPFx package to Site Collection App Catalog
      - name: Upload SPFx to Collection
        shell: bash
        run: m365 spo app add --filePath ./FILENAME --appCatalogUrl ${{ inputs.sharepoint_app_catalogue_url }} --scope ${{ inputs.sharepoint_app_catalogue_scope }} --overwrite

      # Deploy SPFx package
      - name: Deploy SPFx package
        shell: bash
        run: m365 spo app deploy --name ${{ inputs.sharepoint_app_name }} --appCatalogUrl ${{ inputs.sharepoint_app_catalogue_url }} --scope ${{ inputs.sharepoint_app_catalogue_scope }}

