name: CI

on:
  push:
    branches: [main]

# Variables that are available for all the jobs in the workflow
env:
  SPPKG_FILE_NAME: 'infotechtion-api-consumer.sppkg'
  DEPLOYMENT_SCRIPT: 'DeployAppToSite.ps1'
  SITE_URL: 'https://sharma29470.sharepoint.com/sites/HumanResource'
  APP_NAME: 'infotechtion-api-consumer'
  ADMIN_USERNAME: ${{vars.ADMIN_USERNAME}}
  PASSWORD: ${{secrets.ADMIN_USERNAME}}
