name: "SPFx CICD"
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  CI-SPFx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js runtime 
      - name: Node.js install
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Install npm
      - name: Run npm ci
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      # Bundle and Package
      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      # Install CLI for Microsoft 365
      - run: npm install --global @pnp/cli-microsoft365
        name: Install Office365 CLI
      
      # CLI for Microsoft 365 login action
      - name: M365 login
        run: m365 login --authType certificate --certificateBase64Encoded [MIIKcgIBAzCCCi4GCSqGSIb3DQEHAaCCCh8EggobMIIKFzCCBgAGCSqGSIb3DQEHAaCCBfEEggXtMIIF6TCCBeUGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhmUr1b1p8f7QICB9AEggTY4tI0Ut+8k8RcrXnTd9FHFLrErQeiITCJtdJoY3uVm6iulo4d4aqf385Lv2En2ZDrVEE68BWZzSHu+i/pQRGHHeNybjjyLz4JRn6+Cixq+dt7Vg1acALWj0IsCvnjlYJ+ZesJcgDlBDtpIY6giNXpaaByPBEq4RbaaBbsYQR/jjNShk3j0/Og3fxJOcmnnePgipY0W0ft1YDYPZSNultZ8n+PnjSDxY6c8Sen6Nd/cnPVZENMY13U58toyndSUjPzW83KbCe5y2/aU6r6pvmX+v3unOwZpczTtnuOP9/QBtUQz60D52A2+SgebZy1b0H9IOyhCR4qoOwN+IIcW68nl9kUWmTE4mYga3YyThH7D2SH/tpZtkv92Qzc1wkTNeRvqgH2m6SAcYRQRGEB+sN9BZpzeewqnbl82rDlWB0q9Il1JQ6CYKLzORX8+Al4qlX81Kx1N38cmmYZT0ld4i2Zte6rmk/JR6iQh59JBEqh7rc1jUss4gCIeS2PZUDJwhuabSwCPfH97i4mYUH6ExqOUvBI3e8rxbR7kTIruRxh1CkYmKzXHK50YImn+y/3AfGL7MWK7dwSdxNhN2I03fDBkMFdrPmA7QcP1GtQuS3T2VpSBx14n6C9PD5ABSAMAGfqHDPUM2oaguEXNJhMLHvAfVi7J3eKR41TW/eBcQxUchZWadCDEyccAC0uUGN+oGofaiXKz9nKcokN1Hw+xXYy79HJFJAiOD9yL8eM+mBOnxCVRsnRTRfc1OvvtN/a336Fix9mL6x+GSRKMFyGpCMBeWPUMalrz/lVdXw2FjtOj8aEUAw002pUk/QwcCKYjrlzKArLieBCH68En2EOGFClLPAolmCl3FLobio9TBi0UCqZg+5UgBQM3fcm6la0tITRUBE4lzOrndeP+dya0uawpptmI3f8v8zfAzCOinhGazibF3cBwvxxY6A64Uf6UWgxu7kU5C3ywH0ZU8eTajWWgCYfdtuwiep/HJ285FEMsDCcwrh4j7flva8pE+Tfd6IUHWVCzMLdxVSAE8KKaAyYGgjmUSDOshOmdR6cnl5zPxN0sWsJxXMIkuB+yDdF/FXA3E7V+ixvp1Ya1kmGhLidTBxrK9kQo5LmG8RCcXIL+ilhZ6GfN6D0sajn75V5P240vmv1pljmmGjS7MBNtTILFnnzv1AXz9Sq85g3X3e2P7GasH3IH2tY8W0cr7FUxG9G/uwAAi90gEF6oXUv3h5ibE3x17KPdliLVNXEJW4edtHyrlgEorKmYoSjB7uw07GqNKWfvpyN/WbEF0Ft6Fq/uisKkiZFHuS0etG6+oorsKXEXhw9dYXTHwvkewbT0TzGx1QeB9os8j1+LsPhuJhEmQOq5hyD8gXDdU7s3fxcFGj+RH+BfxqHe+xxdxpkcYjZiAD/2dP9/v5BAeFuHldZ9Sy0dYv4caqULhEMCenIwdhnjJXiHTzZ08SMq2jDhCwIBIjGzNxrTJYRsCM7qBbMOTp/Ng3exdI1hG7PUaeqPEpv854IFBzng8C05XzR0gBrCZ5S11pQhq8LhMcVKlvt392AqmMKX4p6JX7yu2j+VRnuy+Wu/N876VWw0136SSHLCok7qo4+spfNBjHnVEeIbQ48qGxGkb0XWtncW0Yr9wSAtVPXWFPHGjGB0zATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtAGIAZQBlAGUANgBhADYAOAAtADcAYwBjAGIALQA0ADEAYQA2AC0AOQA4AGUAYgAtADgAMQA1AGEAMgBiADEAZABkAGMAYgA2MF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggQPBgkqhkiG9w0BBwagggQAMIID/AIBADCCA/UGCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECEJmgpmOwuOuAgIH0ICCA8hCotmP9UNfFw2i2tK2lz8RamQgJFw/HKTP3b05LYqYoT0xWDQZ94aJSUrGAwbIu1eNhd3TgLpvbL1Q+Ek0UPU1hFhFXdtpv4Uicp61la6cI5luJaba1iOIGyExyGLCIqKEYodTp+MRGV3tq1k7klmWI9TH2OVSygN0DPHzgR2DPV+GAc955RxTR5KGCwh3wy+HbWxIVx3KFnRa2VVLwrrAJdJ5A7vxd/sAbQhaFIa8No7O8s2C0pIUfO6pTwA2DM40OxR76/0N1WaklvAHPgfOWGLTYx1jQ4Xo2pLiK3RGD3Mq2YzXImcof0U9puXT/V48+CeVsNH/5TJtF2DBGp5oIDdSZ1vFcoAG1CcuUOfje8OhUr7E00RWeQRq+Tmn9QlV9492jliRP2IfK0gs9EKUeP6ZS2VJxGxulhvgm2zvNWPOZ74sprVOrjd8PjlLEFqYuQ/OPS6iSQ4m6WpA+2AgXwzn6v9ACbfBwqlkA2JFWs8Y8HFjjTFX+tJS7feW7ZwAfcwLUyV51b/my9MhSMJ69LOSBUXl0+Uj45s1BbTJgcifZOn78cRyG7M2KtHVeDrWtJTMfjrjf9DdPw9ghVH7qz5ecsUNf1yQ4EshFTIzKnVOMxuKBzPNV/mMykOLSWmir78Sq39idwoWd7AaXjblgEfO/QgZcqN3+08qjWWVfN/Ge9YukE+Nt5WJu2wCUItItNh32+9QnkvSguuiF6nZAe9vXC2Bv7B1sh0q4I4Uf0jYjjSEbuXaSYaUkANFNc4DanpuM1iProKg1gdxuejv0SPKyG5KlVVLxr4FBt8OjEwwFJRlWwYdsutqLSxt1HYlAuAAxXBlIx5gh1t99NZd6OBV6CUiadLGpfxqEOThH/LMO07Ioji6H7GDxXoX3T+uTLRKmf95r+HgeXZq+o3ESAdw9iZ5QdXl/MAgvGb7KpRBgH5OOqAGbI2FcXv9V3dwLwwio//YiQAYbCRzWG0I5OGfUroyLr08Mbuw6PsD4TMTso1eZpxU0f2MCpXDuIXdX1L4LNZRoL5+dPSbQu4ZL0dKR1Nu+SKjOynyNOyUAQhfOnUfxBzxpmYQYmP1qJ6u4GFosSK1PPWk8J4iluWRkPq4pRnl2QoOiz0mAAGn0NN0OmoThBya4J/0+3YI55EQwVzcwyclpCnA4NYEv7ovj9jDMcjwfnLpvt6+sp0nlTx7qyw0r5MYqx10Yb4gNzXN056uvCGsio1wRJ8QpGvuKa6S3JASVy49F2ym38ZMzInF5gKPwBIGZNwkBVmHMVTo+AZrS4eb8DA7MB8wBwYFKw4DAhoEFM1/h2CPquGJElrv1yQL20hKyUj8BBSZ6PbTAlC2q9kwLt8wp9M9x1mvNgICB9A=]
    
      - name: SharePoint deploy
        id: deploy
        uses: pnp/action-cli-deploy@v3.0.1
        with:
          APP_FILE_PATH: ./package/infotechtion-api-consumer.sppkg
          OVERWRITE: true

