name: "SPFx CICD"
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  CI-SPFx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js runtime 
      - name: Node.js install
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Install npm
      - name: Run npm ci
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      # Bundle and Package
      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: M365 login
        id: login
        uses: pnp/action-cli-login@v2.2.1
        with:
          ADMIN_USERNAME:  ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD:  ${{ secrets.ADMIN_PASSWORD }}
    
      - name: SharePoint deploy
        id: deploy
        uses: pnp/action-cli-deploy@v3.0.1
        with:
          APP_FILE_PATH: ./package/infotechtion-api-consumer.sppkg
          OVERWRITE: true
