name: "SPFx CICD"
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  CI-SPFx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x

      # Install npm
      - name: Run npm ci
        run: npm ci

      - name: Gulp install
        run: npm i -g gulp

      # Bundle and Package
      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      # Install CLI for Microsoft 365
      - run: npm install --global @pnp/cli-microsoft365
        name: Install Office365 CLI
      
      # CLI for Microsoft 365 login action
      - name: M365 login
        run: m365 login --appId ${{ secrets.APP_ID }} -s ${{ secrets.APP_SECRET_ID }} --tenant ${{ secrets.TENANT_ID }} --t secret
    
      - name: SharePoint deploy
        id: deploy
        uses: pnp/action-cli-deploy@v3.0.1
        with:
          APP_FILE_PATH: ./package/infotechtion-api-consumer.sppkg
          OVERWRITE: true

