name: CI

on:
  push:
    branches: [main]

# Variables that are available for all the jobs in the workflow
env:
  SPPKG_FILE_NAME: 'infotechtion-api-consumer.sppkg'
  DEPLOYMENT_SCRIPT: 'DeployAppToSite.ps1'
  SITE_URL: 'https://sharma29470.sharepoint.com/sites/HumanResource'
  APP_NAME: 'infotechtion-api-consumer'
  ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
  PASSWORD: ${{ secrets.ADMIN_USERNAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 2 jobs called "build and deploy"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        run: echo ${{env.ADMIN_USERNAME}}
